### ISSUE TITLE
CSS inlined svg filters do not work after pipelining compression

### ISSUE THREAD

**Issue by Karmak23** [jazzband/django-pipeline#264]
Hi,

I have this in my Compass SCSS file:

``` css
.not-ready {
  // http://demosthenes.info/blog/534/Cross-browser-Image-Blur-with-CSS
  /* Firefox current versions */
  filter: url("data:image/svg+xml;utf8,<svg version=\'1.1\' xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'blur\'><feGaussianBlur stdDeviation=\'3\' /></filter></svg>#blur");
  @include filter(blur(3px));

  cursor: help;
}
```

It works in `DEBUG` mode on my development machine.

When compressed on production, it doesn't work because spaces are removed in the `url(…)` attribute data:

``` css
.not-ready{-webkit-filter:blur(3px);-moz-filter:blur(3px);filter:blur(3px);filter:url("data:image/svg+xml;utf8,<svgversion='1.1'xmlns='http://www.w3.org/2000/svg'><filterid='blur'><feGaussianBlurstdDeviation='3'/></filter></svg>#blur");cursor:help}
```

Do you have a clue if the space stripped by `django-pipeline` or by `compass`? Is there a way to disable this space removal selectively? (obviously, removing other spaces in the file is the desired behavior). I don't understand why anything inside the double quotes is touched by any of the pipeline involved tools…

Possible workarounds: I could try either encode the `url(…)` content as base64, or put all my filters in an external SVG file and refer to them as only IDs. I didn't try any of these solutions yet, I was busy finding the bug. But keeping my CSS as they are and fixing this “space” bug is a fine solution to me, it keeps my SCSS files readable and not-external (SVG) resources dependant.

regards,
