### ISSUE TITLE
How to handle relative paths and subfolders?

### ISSUE THREAD

**Issue by fletchowns** [jazzband/django-pipeline#352]
Let's say you've got 3 files like this:

./myproject/myapp/static/myapp/css/style.less

``` css
@import 'modules/widget.less';
```

./myproject/myapp/static/myapp/css/modules/widget.less

``` css
.widget-icon {
  background: url('../../img/widget-icon.png') no-repeat;
}
```

./myproject/myapp/static/myapp/img/widget-icon.png

This results in the following error:

> The file 'img/widget-icon.png' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x13481d0>

This makes sense, since style.less will be come style.css and then that relative path becomes incorrect. But I'm not sure how to fix this so that both django-pipeline and the CSS inspection in my IDE are happy, any ideas?
