### ISSUE TITLE
Bug in URL_DETECTOR Regex

### ISSUE THREAD

**Issue by clintonb** [jazzband/django-pipeline#388]
The `URL_DETECTOR` value in `pipeline/compressors/__init__.py` fails for minified CSS files.

``` CSS
/* edx-platform/common/static/css/vendor/ova/video-js.min.css */
@font-face{font-family:VideoJS;src:url(videojs/skin/vjs.eot);src:url(videojs/skin/vjs.eot?#iefix) format('embedded-opentype'),url(videojs/skin/vjs.woff) format('woff'),url(videojs/skin/vjs.ttf) format('truetype');font-weight:400;font-style:normal}
```

``` python
# settings.py
PIPELINE_CSS = {
    'style-xmodule-annotations': {
        'source_filenames': [
            'css/vendor/ova/video-js.min.css',
        ],
        'output_filename': 'css/lms-style-xmodule-annotations.css',
    },
}
```

Calling `python manage.py collectstatic` with the CSS and settings above results in the following output. Note that one path has not been updated. This results in `collectstatic` failing with a message indicating that videojs/skin/vjs.eot cannot be found.

``` CSS
/* Unminified */
@font-face {
    font-family: VideoJS;
    src: url(vendor/ova/videojs/skin/vjs.eot);

    /* Note the incorrect path here */
    src: url(videojs/skin/vjs.eot?#iefix) format('embedded-opentype'), url(vendor/ova/videojs/skin/vjs.woff) format('woff'), url(vendor/ova/videojs/skin/vjs.ttf) format('truetype');
    font-weight: 400;
    font-style: normal
}
```

Please update the regex so that it behaves properly with minified CSS.
